"""`docs/configuration.md`, generated from `Settings` so it cannot drift from it.

    uv run python -m jarvis.config.reference > docs/configuration.md

`tests/test_docs_sync.py` fails when the file on disk is not what this renders.
"""

from pathlib import Path
from typing import Any

from jarvis.config.files import XDG_HOMES
from jarvis.config.permissions import PROTECTED_KEYS
from jarvis.config.settings import GROUPS, Settings, env_var_name, field_group, is_secret

#: Defaults that depend on the machine, written as what they are derived from, so the
#: generated file is the same on every machine that renders it.
SYMBOLIC_DEFAULTS = {
    f"{kind}_dir": f"`${XDG_HOMES[kind][0]}/jarvis` (`{XDG_HOMES[kind][1]}/jarvis`)"
    for kind in ("data", "state", "cache")
}

INTRO = """\
# Configuration

<!-- Generated by `uv run python -m jarvis.config.reference`; do not edit by hand. -->

Every setting Jarvis reads, by the name you set it under. The usual way to set them is
`uv run jarvis setup` (a wizard that asks only for what is missing) or
`uv run jarvis config set KEY VALUE`; `uv run jarvis config list` shows each one with where
its value came from.

**Where they live.** `JARVIS_HOME` (default `$XDG_CONFIG_HOME/jarvis`, which is
`~/.config/jarvis`, on Linux and macOS alike) holds `config.toml` for the plain settings and
`secrets.toml` for the credentials, both readable by you alone. A secret is never put on a
command line: `jarvis config set KEY --stdin` reads it from standard input, and
`--from-env VAR` from a variable. The PIN is not in either file: it lives beside them in
`JARVIS_HOME/pin`, written once (see `SECURITY.md`). Keep that directory out of a
dotfiles repository. What Jarvis keeps is in `DATA_DIR`, `STATE_DIR` and `CACHE_DIR`, the
XDG data, state and cache directories below.

**Which value wins**, first to last: the process environment (a systemd `Environment=`,
say), `secrets.toml`, `config.toml`, and the default below. Nothing is read from the
working directory: an install that still has a `.env` there, or its files in `~/.jarvis`,
moves them with `jarvis migrate`, and `jarvis serve` refuses to start until it has.

**What the running service may change.** Jarvis can change some of its own settings — the
voice model's `set_config` tool, or a subagent running `jarvis config set` in a task — and
only those marked *yes* below, until you say otherwise with `jarvis config unlock KEY` or
`jarvis config lock KEY`. The ones marked *never* are protected: every credential, and
every setting that is a line of defence (who may call, the approval allowlist, spending
caps, deletion, the network, the debug switches). Nothing unlocks them.
"""


def _default(value: Any) -> str:
    if value is None or value == [] or value == {}:
        return ""
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, list):
        return f"`{','.join(map(str, value))}`"
    if isinstance(value, float) and value.is_integer():
        return f"`{int(value)}`"
    return f"`{value}`"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render() -> str:
    """The whole of `docs/configuration.md`."""
    lines = [INTRO]
    for group, title in GROUPS.items():
        names = [name for name in Settings.model_fields if field_group(name) == group]
        lines += [f"## {title}", "", "| Setting | Default | Service may change | What it is |"]
        lines.append("|---|---|---|---|")
        for name in names:
            info = Settings.model_fields[name]
            key = env_var_name(name)
            if name in SYMBOLIC_DEFAULTS:
                default = SYMBOLIC_DEFAULTS[name]
            elif info.is_required():
                default = "*required*"
            else:
                default = _default(info.get_default(call_default_factory=True))
            if is_secret(name):
                default = f"{default} (secret)".strip()
            extra = info.json_schema_extra if isinstance(info.json_schema_extra, dict) else {}
            writable = "never" if key in PROTECTED_KEYS else (
                "yes" if extra.get("service_writable") else "no"
            )
            lines.append(
                f"| `{key}` | {_cell(default)} | {writable} | {_cell(info.description or '')} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write(path: Path) -> None:  # pragma: no cover - the command line below
    path.write_text(render(), encoding="utf-8")


if __name__ == "__main__":  # pragma: no cover
    print(render(), end="")
