"""`docs/configuration.md`, generated from `Settings` so it cannot drift from it.

    uv run python -m jarvis.config.reference > docs/configuration.md

`tests/test_docs_sync.py` fails when the file on disk is not what this renders.
"""

from pathlib import Path
from typing import Any

from jarvis.config.permissions import PROTECTED_KEYS
from jarvis.config.settings import GROUPS, Settings, env_var_name, field_group, is_secret

INTRO = """\
# Configuration

<!-- Generated by `uv run python -m jarvis.config.reference`; do not edit by hand. -->

Every setting Jarvis reads, by the name you set it under. The usual way to set them is
`uv run jarvis setup` (a wizard that asks only for what is missing) or
`uv run jarvis config set KEY VALUE`; `uv run jarvis config list` shows each one with where
its value came from.

**Where they live.** `JARVIS_HOME` (default `~/.jarvis`) holds `config.toml` for the plain
settings and `secrets.toml` for the credentials, both readable by you alone. A secret is
never put on a command line: `jarvis config set KEY --stdin` reads it from standard input,
and `--from-env VAR` from a variable. The PIN is not in either file: it lives in
`DATA_DIR/pin`, written once (see `SECURITY.md`).

**Which value wins**, first to last: the process environment (a systemd `Environment=`,
say), `secrets.toml`, `config.toml`, a legacy `.env` in the working directory (read, never
written; `jarvis config import-env` moves it into the store), and the default below.

**What the running service may change.** Jarvis can change some of its own settings — the
voice model's `set_config` tool, or a subagent running `jarvis config set` in a task — and
only those marked *yes* below, until you say otherwise with `jarvis config unlock KEY` or
`jarvis config lock KEY`. The ones marked *never* are protected: every credential, and
every setting that is a line of defence (who may call, the approval allowlist, spending
caps, deletion, the network, the debug switches). Nothing unlocks them.
"""


def _default(value: Any) -> str:
    if value is None or value == [] or value == {}:
        return ""
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, list):
        return f"`{','.join(map(str, value))}`"
    if isinstance(value, float) and value.is_integer():
        return f"`{int(value)}`"
    return f"`{value}`"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render() -> str:
    """The whole of `docs/configuration.md`."""
    lines = [INTRO]
    for group, title in GROUPS.items():
        names = [name for name in Settings.model_fields if field_group(name) == group]
        lines += [f"## {title}", "", "| Setting | Default | Service may change | What it is |"]
        lines.append("|---|---|---|---|")
        for name in names:
            info = Settings.model_fields[name]
            key = env_var_name(name)
            default = "*required*" if info.is_required() else _default(
                info.get_default(call_default_factory=True)
            )
            if is_secret(name):
                default = f"{default} (secret)".strip()
            extra = info.json_schema_extra if isinstance(info.json_schema_extra, dict) else {}
            writable = "never" if key in PROTECTED_KEYS else (
                "yes" if extra.get("service_writable") else "no"
            )
            lines.append(
                f"| `{key}` | {_cell(default)} | {writable} | {_cell(info.description or '')} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write(path: Path) -> None:  # pragma: no cover - the command line below
    path.write_text(render(), encoding="utf-8")


if __name__ == "__main__":  # pragma: no cover
    print(render(), end="")
